# 这些是资助此仓库开发者的方式

github: [Aceyuan361]
patreon: # 替换为你的 Patreon 页面
open_collective: # 替换为你的 OpenCollective 页面
ko_fi: # 替换为你的 Ko-fi 页面
tidelift: # 替换为你的 Tidelift 页面
community_bridge: # 替换为你的 Community Bridge 页面
liberapay: # 替换为你的 Liberapay 页面
issuehunt: # 替换为你的 IssueHunt 页面
otechie: # 替换为你的 Otechie 页面
custom: ['https://www.buymeacoffee.com/yourusername']  # 替换为你的自定义链接
