import type { MetricCardConfig } from '@/types';

export const ALL_METRIC_CARDS: MetricCardConfig[] = [
  {
    metricId: 'cpu',
    title: 'CPU Usage (%)',
    color: '#00f2ff',
    yMin: 0,
    yMax: 100,
    decimals: 0,
    unit: '%',
    enabled: true,
    priority: 1,
  },
  {
    metricId: 'memory',
    title: 'Memory Usage (MB)',
    color: '#7000ff',
    yMin: 0,
    decimals: 0,
    unit: 'MB',
    enabled: true,
    priority: 2,
  },
  {
    metricId: 'fps',
    title: 'Frame Rate (FPS)',
    color: '#ffb400',
    decimals: 0,
    unit: 'FPS',
    enabled: true,
    priority: 3,
  },
  {
    metricId: 'network_up',
    title: 'Network Upload (KB/s)',
    color: '#00ff87',
    yMin: 0,
    decimals: 1,
    unit: 'KB/s',
    enabled: true,
    priority: 4,
  },
  {
    metricId: 'network_down',
    title: 'Network Download (KB/s)',
    color: '#0062ff',
    yMin: 0,
    decimals: 1,
    unit: 'KB/s',
    enabled: true,
    priority: 5,
  },
];
